# Generated by Django 2.2.3 on 2019-08-07 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestapp', '0002_auto_20190807_0637'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginClass',
            fields=[
                ('username', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('dob', models.CharField(default=False, max_length=20)),
            ],
        ),
    ]
