# Generated by Django 2.2.3 on 2019-08-08 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestapp', '0003_loginclass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationform',
            name='personPhoto',
            field=models.ImageField(upload_to='images1/'),
        ),
        migrations.AlterField(
            model_name='applicationform',
            name='signaturePhoto',
            field=models.ImageField(upload_to='images1/'),
        ),
    ]
