# Generated by Django 2.2 on 2019-08-08 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestapp', '0004_auto_20190808_0418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationform',
            name='personPhoto',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='applicationform',
            name='signaturePhoto',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
